<a href="https://colab.research.google.com/github/pruthviraj435/GAI_2303A52181/blob/main/GAI_ASS_1_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Y_actual = np.array([20, 30, 40, 50, 60])
Y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

mae_manual = np.mean(np.abs(Y_actual - Y_pred))
mse_manual = np.mean((Y_actual - Y_pred) ** 2)
rmse_manual = np.sqrt(mse_manual)
r2_manual = 1 - (np.sum((Y_actual - Y_pred) ** 2) / np.sum((Y_actual - np.mean(Y_actual)) ** 2))

print(f"Manual MAE: {mae_manual}")
print(f"Manual MSE: {mse_manual}")
print(f"Manual RMSE: {rmse_manual}")
print(f"Manual R2: {r2_manual}")

mae_lib = mean_absolute_error(Y_actual, Y_pred)
mse_lib = mean_squared_error(Y_actual, Y_pred)
rmse_lib = np.sqrt(mse_lib)
r2_lib = r2_score(Y_actual, Y_pred)

print(f"Library MAE: {mae_lib}")
print(f"Library MSE: {mse_lib}")
print(f"Library RMSE: {rmse_lib}")
print(f"Library R2: {r2_lib}")


Manual MAE: 0.4600000000000016
Manual MSE: 0.24600000000000147
Manual RMSE: 0.49598387070549127
Manual R2: 0.99877
Library MAE: 0.4600000000000016
Library MSE: 0.24600000000000147
Library RMSE: 0.49598387070549127
Library R2: 0.99877


In [5]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

Y_actual = np.array([0, 0, 1, 1, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2, 2])
Y_pred = np.array([0, 0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 2, 1, 2, 2])

accuracy_manual = np.mean(Y_actual == Y_pred)
precision_manual = np.sum((Y_actual == Y_pred) & (Y_actual == 1)) / np.sum(Y_pred == 1) if np.sum(Y_pred == 1) > 0 else 0
recall_manual = np.sum((Y_actual == Y_pred) & (Y_actual == 1)) / np.sum(Y_actual == 1) if np.sum(Y_actual == 1) > 0 else 0
f1_manual = 2 * (precision_manual * recall_manual) / (precision_manual + recall_manual) if precision_manual + recall_manual > 0 else 0
confusion_matrix_manual = np.zeros((3, 3), dtype=int)
for true, pred in zip(Y_actual, Y_pred):
    confusion_matrix_manual[true][pred] += 1

print(f"Manual Accuracy: {accuracy_manual}")
print(f"Manual Precision: {precision_manual}")
print(f"Manual Recall: {recall_manual}")
print(f"Manual F1-Score: {f1_manual}")
print(f"Manual Confusion Matrix:\n{confusion_matrix_manual}")

accuracy_lib = accuracy_score(Y_actual, Y_pred)
precision_lib = precision_score(Y_actual, Y_pred, average='weighted', labels=np.unique(Y_pred))
recall_lib = recall_score(Y_actual, Y_pred, average='weighted', labels=np.unique(Y_pred))
f1_lib = f1_score(Y_actual, Y_pred, average='weighted', labels=np.unique(Y_pred))
confusion_matrix_lib = confusion_matrix(Y_actual, Y_pred)

print(f"Library Accuracy: {accuracy_lib}")
print(f"Library Precision: {precision_lib}")
print(f"Library Recall: {recall_lib}")
print(f"Library F1-Score: {f1_lib}")
print(f"Library Confusion Matrix:\n{confusion_matrix_lib}")



Manual Accuracy: 0.7333333333333333
Manual Precision: 0.75
Manual Recall: 0.75
Manual F1-Score: 0.75
Manual Confusion Matrix:
[[3 1 2]
 [1 3 0]
 [0 0 5]]
Library Accuracy: 0.7333333333333333
Library Precision: 0.738095238095238
Library Recall: 0.7333333333333333
Library F1-Score: 0.7177777777777777
Library Confusion Matrix:
[[3 1 2]
 [1 3 0]
 [0 0 5]]
